
# 在线模式
# true - 使用UUID识别玩家
# false - 使用玩家名识别玩家
# auto - 根据服务器当前是否开启在线模式，来确定是 true 还是 false
# 在正式投入使用该插件之后不应该修改这个值
online-mode: auto

# 飞行时间每日重置时间
reset-time: '4:00'

# 世界相关设置
worlds:
  # 世界处理模式
  # 此处的“指定世界”指的是
  # - 如果白名单不为空，则“指定世界”为白名单世界去除黑名单世界
  # - 如果白名单为空，则“指定世界”为所有世界去除黑名单世界
  # 可以使用以下处理模式
  # HANDLE_ALL - 只有“指定世界”可以飞行，其它世界禁止飞行
  # NOT_HANDLE - 只有“指定世界”可以使用本插件飞行，从“指定世界”进入其它世界，或者进入服务器时位置在其它世界，则关闭玩家的飞行
  mode: HANDLE_ALL
  # 白名单世界，不区分大小写
  whitelist: []
  # 黑名单世界，不区分大小写
  blacklist: []

time-format:
  hour: '%d时'
  hours: '%d时'
  minute: '%d分'
  minutes: '%d分'
  second: '%d秒'
  seconds: '%d秒'
  infinite: '无限'

# 飞行时间消耗顺序
# 默认为先消耗额外时间，额外时间不够再消耗基础时间
time-consume-order:
  - extra
  - standard

boss-bar:
  # 剩余时间显示方式
  # NONE 不显示
  # ACTION_BAR 显示在物品栏上方 (会与其它同样发送这种消息的插件冲突)
  # BOSS_BAR 显示在 BOSS 血条 (在 1.9+ 兼容性最好，在 1.8 会自动降级为 ACTION_BAR)
  display-mode: BOSS_BAR
  # 剩余飞行时间显示内容，支持 PAPI 变量
  flying: '&f剩余飞行时间: &e%format%'
  # 血条颜色，https://javadoc.mcio.dev/spigot/1.21.4/org/bukkit/boss/BarColor.html
  color: BLUE
  # 血条样式，https://javadoc.mcio.dev/spigot/1.21.4/org/bukkit/boss/BarStyle.html
  style: SEGMENTED_10

hook:
  dominion:
    # 在 dominion 领地内是否允许无限飞行
    infinite-fly: true
  residence:
    # 在 residence 领地内是否允许无限飞行
    infinite-fly: true